# site settings
title: Eduardo Lezcano
subtitle: Blog
email: contact@eduardolezcano.com 
description: And this is my personal page
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://eduardolezcano.com" # the base hostname & protocol for your site
author: Eduardo Lezcano Álvarez
street_address: 
city: 
state: 
zip_code: 
country: 
phone: 

paginate: 12
paginate_path: "/blog/page:num/"

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 12 

socials:
  GitHub: https://github.com/edupo
  GitLab:
  Google-Plus: 
  Instagram:
  LinkedIn: https://www.linkedin.com/in/eduardolezcano/
  Twitter: 
  Facebook:
  Slack:
  Itch-io: https://edupo.itch.io/

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: [head, body]
  
# build settings
markdown: kramdown

sass:
  sass_dir: _sass
  sourcemap: never
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
